### ISSUE TITLE
Can this be used with custom modules in SuiteCRM?

### ISSUE THREAD

**Issue by GirlieNinja** [RussellJuma/PySuiteCRM#1]
We have created custom modules and would like to use this API in order to pull data from them. Can this be used to do that? If so do you have some instructions you can share?

**Comment by GirlieNinja** [comment]
Nevermind! Figured it out!

**Comment by RussellJuma** [comment]
> Nevermind! Figured it out!

What was the solution?
See "Limitations Get cannot filter on custom fields due to bug #[7285 ](https://github.com/salesagility/SuiteCRM/issues/7285)in SuiteCRM."

**Comment by GirlieNinja** [comment]
That bug is resolved in SuiteCRM, but I guess technically I was searching for a custom field and it worked. I just added my custom module to SuiteCRM.py  and was able to do a get on it using a custom field after that.

**Comment by Hiranyaloka** [comment]
Hi Russell,

I've successfully added custom and modules to the "_modules" definition, which works fine, but I'd prefer to be able to declare the custom modules in a configuration file.  And while I'm requesting features, I'll add that it'd be useful to alias the module name(s) in a configuration file. For example, here's a custom module, and a SalesAgility "AOS" module that I've added and aliased in the "_modules" definition:
`self.Teacher = Module(self, 'et123_Teacher')`
`self.ProgramOffering = Module(self, 'AOS_Products')`

Once again, thanks for PySuiteCRM!!!!

- Rick
