### ISSUE TITLE
Get method on phone_mobile field, not working

### ISSUE THREAD

**Issue by nima0102** [RussellJuma/PySuiteCRM#4]
Hello Russell, 

First of all, really appreciate your awesome python module. 
In our use case, we need to search based on "**phone_mobile**" field which is a built-in field ( not custom field ). We store the phone_mobile in "+[country code][phone number] format. 

after doing lots of trial and error, it turned out that if we store phone_mobile without "+", get method can find otherwise it would not find any matched record. 

example: 
- ) stored phone_mobile =  +999333333
result = suitecrm.Contacts.get(phone_mobile=''+999333333") ( NOT working )

- ) stored phone_mobile =  992222222
result = suitecrm.Contacts.get(phone_mobile=''992222222") ( working )

Can you please advise? 

thanks.

**Comment by RussellJuma** [comment]
It is case sensitive. How is the number stored for that record?
ie... 626-555-555 (record actual data in the contact)

```python
suitecrm.Contacts.get(phone_mobile=626555555) # No record found
suitecrm.Contacts.get(phone_mobile=(+1626555555) # No record found
suitecrm.Contacts.get(phone_mobile=(626-555-555) # Record found
```

You can always run `suitecrm.Contacts.fields()` to get the list of fields that are searchable.

**Comment by nima0102** [comment]
@RussellJuma Thank you so much for your quick reply. 
I just updated the comment. 

we store the number with this format : +[country code][actual phone number]
example: +999333333


but after changed the store format to [country code][actual phone number] ( example 999333333 ) without "+" character, now it is working as we expect.

**Comment by RussellJuma** [comment]
No worries, glad I could help. You can always run `suitecrm.Contacts.fields()` to get the list of fields that are searchable.

**Comment by nima0102** [comment]
still there is a bug

in order to replicate:

- store phone_mobile "+991111111"
- use get method : 
  suitecrm.Contacts.get(phone_mobile=''+991111111")

above scenario would not work.

**Comment by RussellJuma** [comment]
I have found the problem.

**Comment by RussellJuma** [comment]
phone number special character was causing problems with the url encoding.

**Comment by nima0102** [comment]
@RussellJuma Perfect. thanks. 
I am glad to report this bug and thank you for your support!

**Comment by RussellJuma** [comment]
Already ready.
